version: '3.8'

services:
  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
    depends_on:
      - jwt-create
      - jwt-verify
      - front-public

  jwt-create:
    build: ./back/jwt-create
    ports:
      - "3001:3001"

  jwt-verify:
    build: ./back/jwt-verify
    ports:
      - "3002:3002"

  front-public:
    build: ./front/public
    ports:
      - "3000:3000"
