version: '3.1'

services:
  vp321.nginx:
    build:
      context: ./services/nginx
      dockerfile: ./Dockerfile
    container_name: nginx_container
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - vp321.api.jwt-create
      - vp321.api.jwt-verify
      - vp321.front.public
    networks:
      - app-network

  vp321.api.jwt-create:
    build:
      context: ./back/jwt-create
      dockerfile: ./Dockerfile
    container_name: jwt_create_container
    environment:
      - JWT_SECRET=your_jwt_secret_key
    ports:
      - "3939:3000"
    networks:
      - app-network

  vp321.api.jwt-verify:
    build:
      context: ./back/jwt-verify
      dockerfile: ./Dockerfile
    container_name: jwt_verify_container
    environment:
      - JWT_SECRET=your_jwt_secret_key
    ports:
      - "3034:3000"
    networks:
      - app-network

  vp321.front.public:
    build:
      context: ./front/public
      dockerfile: ./Dockerfile
    container_name: front_public_container
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
