version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend_1
      - backend_2

  backend_1:
    build:
      context: ./backend
    environment:
      - PORT=3001
    expose:
      - "3001"

  backend_2:
    build:
      context: ./backend
    environment:
      - PORT=3002
    expose:
      - "3002"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
